config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :workouts do
    resources :excercises do
      resources :circuits
    end
  end
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circuit.rb
class Circuit < ApplicationRecord
    belongs_to :excercise
end

app/models/excercise.rb
class Excercise < ApplicationRecord
  belongs_to :workout
  validates :setrep, presence: true
  validates :box11, presence: true, numericality: true
  validates :box12, presence: true, numericality: true
  validates :box13, presence: true, numericality: true
  validates :box21, presence: true, numericality: true
  validates :box22, presence: true, numericality: true
  validates :box23, presence: true, numericality: true
end

app/models/workout.rb
class Workout < ApplicationRecord
    has_many :excercises, dependent: :destroy
    validates :name, presence: true
    validates :group, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/circuits_controller.rb
class CircuitsController < ApplicationController
    def create
        @workout = Workout.find(params[:workout_id])
        @excercise = Excercise.find(params[:excercise_params])
        @circuit =  @workout.excercises.circuit.create(circuit_params)
        redirect_to workout_path(@workout)
    end
    
    def destroy
        @workout = Workout.find(params[:workout_id])
        @excercise = Excercise.find(params[:excercise_id])
        @circuit = Circuit.find(params[:id])
        @circuit.destroy
        
        redirect_to workout_path(@workout)
    end
end
    private
        def circuit_params
            params.require(:circuit).permit(:weight, :reps)
        end

app/controllers/excercises_controller.rb
class ExcercisesController < ApplicationController
    def create
        @workout = Workout.find(params[:workout_id])
        @excercise = @workout.excercises.create(excercise_params)
        redirect_to workout_path(@workout)
    end
    
    def show
        @excercise = Excercise.find(params[:id])
    end
    def edit
        @workout = Workout.find(params[:id])
        @excercise = Excercise.find(params[:workout_id])
    end
    def update
        @workout = Workout.find(params[:workout_id])
        @excercise = Excercise.find(params[:id])
        
        if @excercise.update(excercise_params)
            redirect_to @workout
        else
            render 'edit'
        end
    end
    
    def destroy
        @workout = Workout.find(params[:workout_id])
        @excercise = Excercise.find(params[:id])
        @excercise.destroy
        
        redirect_to workout_path(@workout)
    end
  
    private
        def excercise_params
            params.require(:excercise).permit(:setrep, :box11, :box12, :box13, :box21, :box22, :box23)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to workouts_path(@workout)
  end
end

app/controllers/workout_controller.rb
class WorkoutController < ApplicationController
    def new
       @workout = Workout.new
    end
    def index
        @workouts = Workout.all
    end
    def create
        @workout = Workout.new(workout_params)
        if @workout.save
            redirect_to @workout
        else
            render 'new'
        end
    end
    def show
        @workout = Workout.find(params[:id])
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    def new
       @workout = Workout.new
    end
    
    def index
        @workouts = Workout.all
    end
    
    def create
        @workout = Workout.new(workout_params)
        if @workout.save
            redirect_to @workout
        else
            render 'new'
        end
    end
    
    def edit
        @workout = Workout.find(params[:id])
    end
    
    def update
        @workout = Workout.find(params[:id])
        
        if @workout.update(workout_params)
            redirect_to @workout
        else
            render 'edit'
        end
    end    
    
    def destroy
        @workout = Workout.find(params[:id])
        @workout.destroy
        
        redirect_to workouts_path
    end
    
    def show
        @workout = Workout.find(params[:id])
    end
    
  
end

private
    def workout_params
        params.require(:workout).permit(:name, :group)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circuits_helper.rb
module CircuitsHelper
end

app/helpers/excercises_helper.rb
module ExcercisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workout_helper.rb
module WorkoutHelper
end

app/views/excercises/_excercise.html.erb
    <p id= "ExID">
        <!--Exercise Name:-->
        
        <h3><%= excercise.setrep %></h3>
    </p>
 
    
    <p id= "ExID">
        <!--Exercise Info:-->
        Weight: 
        <strong><%= excercise.box11 %></strong>
        &nbsp;&nbsp;Reps: 
        <strong><%= excercise.box12 %></strong>
        <br> Weight: 
        <strong><%= excercise.box13 %></strong>
        &nbsp;&nbsp;Reps: 
        <strong><%= excercise.box21 %></strong>
        <br> Weight: 
        <strong><%= excercise.box22 %></strong>
        &nbsp;&nbsp;Reps: 
        <strong><%= excercise.box23 %></strong>
    </p> 
        
    <p id= "CRUD_small">
        <td><%= link_to 'Edit Exercise', edit_workout_excercise_path(excercise) %></td> 
        <br>
          

        <%= link_to 'Destroy Exercise', [excercise.workout, excercise],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
    <br><br>
    </p>

app/views/excercises/_form.html.erb
<%= form_for([@workout, @workout.excercises.build]) do |f| %>
<table>
  <tr>
    <th><%= f.text_field :setrep %></th>
    <th>Weight</th> 
    <th>Reps</th>
  </tr>
  <tr>
    <td>Set 1</td>
    <td><%= f.text_area :box11 %></td>
    <td><%= f.text_area :box12 %></td>
  </tr>
  <tr>
    <td>Set 2</td>
    <td><%= f.text_area :box13 %></td>
    <td><%= f.text_area :box21 %></td>
  </tr>
  <tr>
    <td>Set 3</td>
    <td><%= f.text_area :box22 %></td>
    <td><%= f.text_area :box23 %></td>
  </tr>
</table>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/excercises/edit.html.erb
<h1>Editing Exercise</h1>
 <%= form_for([@workout, @excercise]) do |f| %>
   <% if @excercise.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@excercise.errors.count, "error") %> prohibited
        this exercise from being saved:
      </h2>
      <ul>
        <% @excercise.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <th><%= f.text_field :setrep %></th>
    <th>Weight</th> 
    <th>Reps</th>
  </tr>
  <tr>
    <td>Set 1</td>
    <td><%= f.text_area :box11 %></td>
    <td><%= f.text_area :box12 %></td>
  </tr>
  <tr>
    <td>Set 2</td>
    <td><%= f.text_area :box13 %></td>
    <td><%= f.text_area :box21 %></td>
  </tr>
  <tr>
    <td>Set 3</td>
    <td><%= f.text_area :box22 %></td>
    <td><%= f.text_area :box23 %></td>
  </tr>
</table>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', workouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Werkit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>WERKIT</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'My Workouts', controller: 'workouts' %>

app/views/workout/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :descriptions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workout_path %>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>
 
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@workout.errors.count, "error") %> prohibited
        this workout from being saved:
      </h2>
      <ul>
        <% @workout.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </p>
 
  <p>
    <%= f.submit class: 'create_workout' %>

  </p>
 
<% end %>

app/views/workouts/_workout.html.erb
<p>
    <strong>Exercise Name:</strong>
    <%= excercise.setrep %>
</p>
    <strong>Exercise Info:</strong>
    <%= excercise.box11 %>
    <%= excercise.box12 %>
    <%= excercise.box13 %>
    <%= excercise.box21 %>
    <%= excercise.box22 %>
    <%= excercise.box23 %>

<p>
    <%= link_to 'Destroy Workout', [exercise.workout, exercise],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</p>

app/views/workouts/edit.html.erb
<h1>Editing Workouts</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>Listing workouts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Group</th>
  </tr>
 
  <% @workouts.each do |workout| %>
    <tr>
      <td id="workout-title"><%=  link_to workout.name, workout_path(workout) %></td>
      <td><%= workout.group %></td>
      <td><%= link_to 'Edit', edit_workout_path(workout) %></td>    
      <td><%= link_to 'Destroy',
          workout_path(workout),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<p id="new_workout_button"><%= link_to 'New Workout', new_workout_path %></p>

app/views/workouts/new.html.erb
<h1>New Workout</h1>
<%= render 'form' %>
<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p>
  <strong>Displaying Workout</strong>
</p>
<p>
  <strong>Name:</strong>
  <%= @workout.name %>
</p>
 
<p>
  <strong>Group:</strong>
  <%= @workout.group %>
</p>

<h2>Exercises</h2>
<p>
 <%= render @workout.excercises %> 
</p>

<h2>Add an exercise:</h2>

  <%= render 'excercises/form' %>


<%= link_to 'Back', workouts_path %>